import {
  DataProcessor,
  processDataForDonutChart,
  processBarChartData,
  processPieChartData,
} from "../../services/chartProcessors";

export interface ChartConfig {
  id: string;
  title: string;
  // ChartData will be generated by the processor.
  chartData: ReturnType<DataProcessor>;
}

// Chart definition couples the configuration with its processing function.
export interface ChartDefinition {
  id: string;
  title: string;
  targetColumns?: string[];
  processor: DataProcessor;
}

// Centralized list of chart definitions.
export const chartDefinitions: ChartDefinition[] = [
  {
    id: "card1",
    title: "Online Rating Index (ORI)",
    targetColumns: ["Online Rating Index"],
    processor: processDataForDonutChar,
  },
  {
    id: "card2",
    title: "STEP Index",
    targetColumns: ["STEP_Index"],
    processor: processDataForDonutChart,
  },
  {
    id: "card3",
    title: "Voice Map",
    processor: processPieChartData,
  },
];
